#! /bin/sh

export TERMINAL="${HOME}/.suckless/st/st"

sxhkd -s &
dunst &
killall polybar
polybar main &
xsetroot -cursor_name left_ptr &
~/.fehbg &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config normal_border_color \#272727
bspc config active_border_color \#ebdbb2
bspc config focused_border_color \#ebdbb2
bspc config presel_feedback_color \#989719 

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -r *
bspc rule -a "Google-chrome" desktop='^1' follow=on
